networks:
  mynet:
    driver: bridge

services:
  intake:
    build:
      context: ./chir-intake-proto1
    container_name: "intake"
    ports:
      - "8080:8080/tcp"
    networks:
      - mynet
    depends_on:
      - dal

  dal:
    build:
      context: ./chmr-dal-proto1
    container_name: "dal"
    networks:
      - mynet
    depends_on:
      - redis-server

  redis-query:
    build:
      context: ./redis-query
    container_name: "redis-query"
    ports:
      - "8088:80/tcp"
    networks:
      - mynet
    depends_on:
      - redis-server

  redis-server:
    image: redis:latest
    container_name: "redis-server"
    networks:
      - mynet